import { Student, Classroom } from '../types/observation';

export const REAL_CLASSROOMS: Classroom[] = [
  { id: "playhome", name: "Playhome", ageGroup: "Playhome", teacherName: "Manasa T, Shilpa S" },
  { id: "nursery_jnana", name: "Nursery Jnana", ageGroup: "Nursery", teacherName: "Swetha R" },
  { id: "nursery_satya", name: "Nursery Satya", ageGroup: "Nursery", teacherName: "Tejashree" },
  { id: "nursery_shourya", name: "Nursery Shourya", ageGroup: "Nursery", teacherName: "Anusha" },
  { id: "lkg_jnana", name: "LKG Jnana", ageGroup: "LKG", teacherName: "Swathi CN, Bhavana L" },
  { id: "lkg_satya", name: "LKG Satya", ageGroup: "LKG", teacherName: "Lakshmi Devi" },
  { id: "lkg_shourya", name: "LKG Shourya", ageGroup: "LKG", teacherName: "Manasa M" },
  { id: "lkg_samriddhi", name: "LKG Samriddhi", ageGroup: "LKG", teacherName: "Shilpa T" },
  { id: "ukg_jnana", name: "UKG Jnana", ageGroup: "UKG", teacherName: "Aruna E, G Swathi" },
  { id: "ukg_satya", name: "UKG Satya", ageGroup: "UKG", teacherName: "Shruthi T" },
  { id: "ukg_shourya", name: "UKG Shourya", ageGroup: "UKG", teacherName: "Ashwini KJ" },
  { id: "ukg_samriddhi", name: "UKG Samriddhi", ageGroup: "UKG", teacherName: "Nirmala, G Swathi" },
];

export const REAL_STUDENTS: Student[] = [
  { id: "playhome_1_aarna_ka", name: "Aarna KA", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_2_heshvi_mr", name: "Heshvi MR", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_3_hitiksha", name: "Hitiksha", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_4_hanvika_koka", name: "Hanvika Koka", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_5_aluru_aryan_kar", name: "Aluru Aryan karthikeya", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_6_sathvik_m", name: "Sathvik M", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_7_raghunandan_a", name: "Raghunandan A", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_8_mokshith_g_n", name: "Mokshith G N", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_9_hanvika_gowda", name: "Hanvika Gowda", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_10_heyansh", name: "Heyansh", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "playhome_11_trivikram_virat", name: "Trivikram virat SM", classroomId: "playhome", classroomName: "Playhome", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_1_aarush_c_r", name: "Aarush C R", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_2_amyra_fathima", name: "Amyra Fathima", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_3_charvik", name: "Charvik", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_4_chirag_jain_j", name: "Chirag Jain.J", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_5_ghaziya_anam_i", name: "Ghaziya Anam.I", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_6_janani_g_r", name: "Janani  G R", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_7_jashwik_g", name: "Jashwik.G", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_8_lishika_sairaj", name: "Lishika sairaj", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_9_lovik_m", name: "Lovik M", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_10_panvith_g_b", name: "Panvith.G.B", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_11_pranvita_p", name: "Pranvita.P", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_12_riya_p", name: "Riya.P", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_13_preritha_as", name: "Preritha AS", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_14_rushika_s", name: "Rushika.S", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_15_sandhyareddyk_s", name: "SandhyaReddyK.S", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_16_sampada_sri_man", name: "Sampada sri Manju", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_17_sushruth_s", name: "Sushruth S", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_18_thanvitha_b", name: "Thanvitha.B", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_19_vijay_sai", name: "Vijay sai", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_20_waarith_j", name: "Waarith.J", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_21_vibhu_p", name: "Vibhu.P", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_jnana_22_dhanya", name: "Dhanya", classroomId: "nursery_jnana", classroomName: "Nursery Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_1_ridhi_reddy", name: "Ridhi Reddy", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_2_venkata_gharshi", name: "Venkata Gharshith Gurram", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_3_vadite_vedantik", name: "Vadite Vedantika", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_4_sahasra_siri_m", name: "Sahasra Siri.M", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_5_samarth_s", name: "Samarth.S", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_6_varnika_r", name: "Varnika R", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_7_prudhvi_v_raj", name: "Prudhvi v raj", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_8_p_j_manyu_ram", name: "P.J Manyu Ram", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_9_l_s_harsha", name: "L S Harsha", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_10_aishaani_p_y", name: "Aishaani P Y", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_11_kruti_m_roy", name: "Kruti. M. Roy", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_12_jhareesh_h", name: "Jhareesh.H", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_13_jhansi_b", name: "Jhansi B", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_14_gayatri_v", name: "Gayatri.V", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_15_haneesh_a_r", name: "Haneesh.A.R", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_16_dibyanshu_panda", name: "Dibyanshu Panda", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_17_gavinn_krusshna", name: "Gavinn Krusshna.S", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_18_dhanvith_kotres", name: "Dhanvith kotresh M J", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_19_ganavi_b_n", name: "Ganavi B N", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_20_avyaan_pruthvi_", name: "Avyaan Pruthvi Raj", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_satya_21_moulya_ps", name: "Moulya PS", classroomId: "nursery_satya", classroomName: "Nursery Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_1_mohammad_izhaan", name: "Mohammad Izhaan", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_2_yukthi_anantha", name: "Yukthi Anantha", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_3_vrinda_k_m", name: "Vrinda k M", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_4_takshvi_sai_t_p", name: "Takshvi sai T P", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_5_haripriya_v", name: "Haripriya V", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_6_kushanth_raj_n_", name: "Kushanth Raj.N.P", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_7_punarvi_reddy_s", name: "Punarvi Reddy. S", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_8_hemanandan_m", name: "Hemanandan.M", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_9_uthsav_ray_s_p", name: "Uthsav Ray.S.P", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_10_shyam_kumar_t_m", name: "Shyam Kumar.T M", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_11_durgacharan_r_t", name: "Durgacharan.R.T", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_12_krishiv_g_m", name: "Krishiv. G.M", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_13_anarghya_varcha", name: "Anarghya Varchasvi.T", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_14_n_shravan", name: "N.Shravan", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_15_nishvika_a", name: "Nishvika A", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_16_aradhya_k", name: "Aradhya.K", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_17_kridha_m_s", name: "Kridha M.S", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_18_brundan_prasad", name: "Brundan Prasad", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_19_aarush_krisna", name: "Aarush Krisna", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_20_ridvika_m", name: "Ridvika M", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "nursery_shourya_21_megha_sreekanth", name: "Megha Sreekanth Pawar", classroomId: "nursery_shourya", classroomName: "Nursery Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_1_akira_nandan_m", name: "Akira Nandan M", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_2_akeer_nayaka_e", name: "Akeer Nayaka E", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_3_ashvik_saini", name: "Ashvik Saini", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_4_c_p_janani", name: "C P Janani", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_5_dakshatha_b_n", name: "Dakshatha B N", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_6_druthi_s_m", name: "Druthi S M", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_7_g_r_sharnya", name: "G R Sharnya", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_8_g_v_yaduveer_kr", name: "G V Yaduveer Krishna", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_9_gowtham_yadav_r", name: "Gowtham Yadav R", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_10_hari_charan_h", name: "Hari Charan H", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_11_havya_ajith", name: "Havya Ajith", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_12_hruday_pawar_v_", name: "Hruday Pawar V M", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_13_janav_m_h", name: "Janav M H", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_14_kanvikraj_s", name: "Kanvikraj S", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_15_koushik_kumar_m", name: "Koushik Kumar M V", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_16_m_kundan_yuvara", name: "M Kundan Yuvaraj", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_17_mahima_m", name: "Mahima M", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_18_mahitha_m", name: "Mahitha M", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_19_pavani_r", name: "Pavani R", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_20_prisha_s", name: "Prisha S", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_21_priyanka_s_v", name: "Priyanka S V", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_22_rishi_p", name: "Rishi P", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_23_riya_k", name: "Riya K", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_24_shivaan_p_nidga", name: "Shivaan P Nidgal", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_25_shlok_s", name: "Shlok S", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_26_stuti_jain_j", name: "Stuti Jain J", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_27_syeda_tabsira_n", name: "Syeda Tabsira Noor", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_jnana_28_varun_kumar_v", name: "Varun Kumar V", classroomId: "lkg_jnana", classroomName: "LKG Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_1_advitha_t_s", name: "Advitha T S", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_2_ashvitha_j", name: "Ashvitha J", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_3_atharv_sai_gupt", name: "Atharv Sai Gupta B A", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_4_avani_p", name: "Avani P", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_5_dhushyanth_m_s", name: "Dhushyanth M S", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_6_dikshita_prajap", name: "Dikshita Prajapati", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_7_gahan_sai_agast", name: "Gahan Sai Agastya R K", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_8_gamya_sai_aksha", name: "Gamya Sai Akshanga R K", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_9_ganavi_g_m", name: "Ganavi G M", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_10_hanasvi_gowda_g", name: "Hanasvi Gowda G P", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_11_harshith_m", name: "Harshith M", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_12_heshwith_m", name: "Heshwith M", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_13_krushika", name: "Krushika", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_14_likhil_m", name: "Likhil M", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_15_lithvik_gowda_m", name: "Lithvik Gowda M R", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_16_lokya_rakesh_r", name: "Lokya Rakesh R", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_17_manan_nayaka_n_", name: "Manan Nayaka N B", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_18_mokshith_bhagan", name: "Mokshith Bhagan U", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_19_n_a_shravani", name: "N A Shravani", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_20_nithara_gangarp", name: "Nithara Gangarpur", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_21_pappu_ashwanth_", name: "Pappu Ashwanth Kumar", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_22_ridharv_j_r", name: "Ridharv J R", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_23_shiva_kushwah", name: "Shiva Kushwah", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_24_thanvita_v", name: "Thanvita V", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_25_vidhatri_v", name: "Vidhatri V", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_26_yashika_h", name: "Yashika H", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_27_yuvik_a_s", name: "Yuvik A S", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_satya_28_mahaan_s", name: "Mahaan S", classroomId: "lkg_satya", classroomName: "LKG Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_1_aadvik_s_r", name: "Aadvik S R", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_2_b_ruthvik", name: "B Ruthvik", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_3_charvik_n", name: "Charvik N", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_4_charvika_s", name: "Charvika S", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_5_dhakkshith_t_ka", name: "Dhakkshith T Kattemane", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_6_dhyana_daivik_s", name: "Dhyana Daivik S N", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_7_gourav_siddhart", name: "Gourav Siddharth", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_8_hema_t", name: "Hema T", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_9_indrajith_r", name: "Indrajith R", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_10_jayashree_t_m", name: "Jayashree T M", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_11_jishnu_yadav_t_", name: "Jishnu Yadav T P", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_12_laya_a", name: "Laya A", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_13_loukyashree_g_v", name: "Loukyashree G V", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_14_manvith_s", name: "Manvith S", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_15_miheer_amarjeet", name: "Miheer Amarjeet Gaikwad", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_16_mohith_m_r", name: "Mohith M R", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_17_poorvith_a_mara", name: "Poorvith A Maravayi", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_18_prathista_ekana", name: "Prathista Ekana N P", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_19_sara_p_evika", name: "Sara P Evika", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_20_sarika_siri_d_r", name: "Sarika Siri D R", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_21_vanshika_g_r", name: "Vanshika G R", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_22_vihaan_a", name: "Vihaan A", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_23_yashaswi_g", name: "Yashaswi G", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_24_yashika_h", name: "Yashika H", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_25_yashika_m", name: "Yashika M", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_26_yohan_c_gowda", name: "Yohan C Gowda", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_shourya_27_janardhan_b", name: "Janardhan B", classroomId: "lkg_shourya", classroomName: "LKG Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_1_aadhya_navishka", name: "Aadhya Navishka R", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_2_aniketh_g_s", name: "Aniketh G S", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_3_bhavish_reddy_r", name: "Bhavish Reddy R", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_4_dhanvika_m", name: "Dhanvika M", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_5_f_basheerunnisa", name: "F Basheerunnisa", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_6_guturu_naga_nih", name: "Guturu Naga Nihanya", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_7_hrithvik_seervi", name: "Hrithvik Seervi B", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_8_mahika_a", name: "Mahika A", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_9_mohammed_araad", name: "Mohammed Araad", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_10_rithvik_n", name: "Rithvik N", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_11_s_deepika", name: "S Deepika", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "lkg_samriddhi_12_k_p_sarthak_red", name: "K P Sarthak Reddy", classroomId: "lkg_samriddhi", classroomName: "LKG Samriddhi", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_1_aaradhya_s_m", name: "Aaradhya S M", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_2_abhigna_m_k", name: "Abhigna M K", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_3_akhil_s", name: "Akhil S", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_4_ankitha_j", name: "Ankitha J", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_5_atarva_p_mahesh", name: "Atarva P Mahesh", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_6_bhuvan_s", name: "Bhuvan S", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_7_c_r_srinika", name: "C R Srinika", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_8_danvith_yadav", name: "Danvith Yadav", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_9_drish_k_shetty", name: "Drish K Shetty", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_10_drithi_h_m", name: "Drithi H M", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_11_janya_a_s", name: "Janya A S", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_12_k_s_deekshana_d", name: "K S Deekshana Dhatri", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_13_k_v_keshvin", name: "K V Keshvin", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_14_kanishka_kunwar", name: "Kanishka Kunwar", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_15_khushmith_m", name: "Khushmith M", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_16_krishay_ishaan_", name: "Krishay Ishaan Y", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_17_manvith_a", name: "Manvith A", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_18_manyashree_p", name: "Manyashree P", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_19_maulya_h", name: "Maulya H", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_20_mohammed_anas_m", name: "Mohammed Anas M", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_21_n_abhiram_reddy", name: "N Abhiram Reddy", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_22_namana_shashidh", name: "Namana Shashidhar", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_23_neelaj_atharva_", name: "Neelaj Atharva A R", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_24_s_k_vajra_vaibh", name: "S K Vajra Vaibhav", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_25_sadvin_t_yajama", name: "Sadvin T Yajaman", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_26_shivanya_kushwa", name: "Shivanya Kushwah", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_27_utkarsh_b_m", name: "Utkarsh B M", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_jnana_28_varshini_g", name: "Varshini G", classroomId: "ukg_jnana", classroomName: "UKG Jnana", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_1_aarohi_prakash", name: "Aarohi Prakash", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_2_aadithi_s_d", name: "Aadithi S D", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_3_aarush_katta", name: "Aarush Katta", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_4_advith_t", name: "Advith T", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_5_aryan_r", name: "Aryan R", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_6_bhanavi_v_s", name: "Bhanavi V S", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_7_charuni_jai_sim", name: "Charuni Jai Simha", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_8_daivik_aravinda", name: "Daivik Aravinda B A", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_9_dhanvitha_k", name: "Dhanvitha K", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_10_dishan_k_m", name: "Dishan K M", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_11_diyaan_y", name: "Diyaan Y", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_12_girivardhan_s_r", name: "Girivardhan S R", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_13_h_m_viraj", name: "H M Viraj", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_14_hania", name: "Hania", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_15_keshava_reddy", name: "Keshava Reddy", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_16_krishitha_m_n", name: "Krishitha M N", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_17_nihaarika_t", name: "Nihaarika T", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_18_rishyanth_ram", name: "Rishyanth Ram", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_19_rithvika_b_s", name: "Rithvika B S", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_20_sainya_shiva_sa", name: "Sainya Shiva Sai", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_21_sathrasala_maya", name: "Sathrasala Mayanshi", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_22_sheikh_rubza", name: "Sheikh Rubza", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_23_tejas_r_t", name: "Tejas R T", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_24_trivikram", name: "Trivikram", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_25_varsha_t", name: "Varsha T", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_26_vedanth_k_h", name: "Vedanth K H", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_27_yashika_m", name: "Yashika M", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_satya_28_zayn", name: "Zayn", classroomId: "ukg_satya", classroomName: "UKG Satya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_1_bhuvan_nayaka_c", name: "Bhuvan Nayaka C", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_2_chaithra_k", name: "Chaithra K", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_3_chinmayi_sai_ra", name: "Chinmayi Sai Raj", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_4_dimpal_p_r", name: "Dimpal P R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_5_g_s_manvith", name: "G S Manvith", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_6_gagan_kumar", name: "Gagan Kumar", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_7_hanisha_s", name: "Hanisha S", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_8_hanvika_m_l", name: "Hanvika M L", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_9_hithesh_raj_r", name: "Hithesh Raj R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_10_jashwanth_m_a", name: "Jashwanth M A", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_11_jnanavi_r", name: "Jnanavi R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_12_kavya", name: "Kavya", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_13_khushi_a", name: "Khushi A", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_14_kusumanjali_s", name: "Kusumanjali S", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_15_m_suthiksh_gowd", name: "M Suthiksh Gowda", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_16_mayank_sutar_r", name: "Mayank Sutar R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_17_neeraj_aradhya_", name: "Neeraj Aradhya A R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_18_s_kushi", name: "S Kushi", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_19_s_sameeksha", name: "S Sameeksha", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_20_saanvi_r", name: "Saanvi R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_21_sahitya_reddy_k", name: "Sahitya Reddy K S", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_22_shamitha_reddy_", name: "Shamitha Reddy S", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_23_sushanth_gowda_", name: "Sushanth Gowda P S", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_24_vihaan_a_r", name: "Vihaan A R", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_25_vikranth_s", name: "Vikranth S", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_26_yanvitha_b", name: "Yanvitha B", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_27_yash_sai", name: "Yash Sai", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_shourya_28_yashdhara_v", name: "Yashdhara V", classroomId: "ukg_shourya", classroomName: "UKG Shourya", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_1_dhruvith_m_s", name: "Dhruvith M S", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_2_ishaan_g_v", name: "Ishaan G V", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_3_jnapanashree", name: "Jnapanashree", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-teal-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_4_kaveti_chaithvi", name: "Kaveti Chaithvik Royal", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-purple-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_5_kushal_s_v", name: "Kushal S V", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-cyan-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_6_laasya_t", name: "Laasya T", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-orange-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_7_manvik_j_n", name: "Manvik J N", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-indigo-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_8_n_m_dhruvika", name: "N M Dhruvika", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-emerald-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_9_rishika_h", name: "Rishika H", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-rose-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_10_sanvith_t", name: "Sanvith T", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-amber-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_11_trishika", name: "Trishika", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-blue-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
  { id: "ukg_samriddhi_12_syed_arman", name: "Syed Arman", classroomId: "ukg_samriddhi", classroomName: "UKG Samriddhi", avatarColor: "bg-violet-600", active: true, createdAt: '2026-09-01T08:00:00Z' },
];

export const SAMPLE_CLASSROOMS = REAL_CLASSROOMS;
export const INITIAL_STUDENTS = REAL_STUDENTS;
